### ISSUE TITLE
StationConfigurator doesn't handle scaling and validation well

### ISSUE THREAD

**Issue by WilliamHPNielsen** [qdev-dk/qdev-wrappers#176]
As seen in the lab:

When creating a new parameter that is a scaled version of an existing parameter, the validation of the new parameter's values does not correctly match the scaling. As an example, we consider the `DummyInstrument`. We recall that the "gates" by default have validators `<Numbers -800<=v<=400>`.

```yaml
instruments:
  dummy:
    driver: qcodes.tests.instrument_mocks
    type: DummyInstrument
    init:
      gates: ['ch1', 'ch2']

    enable_forced_reconnect: true

    parameters:
      ch1:
        alias: mygate
        scale: 0.001
        unit: mV
```

Now, in python
```python
from qdev_wrappers.station_configurator import StationConfigurator
scfg = StationConfigurator('MFE_conf.yaml')
dummy = scfg.load_instrument('dummy')
```
if we set `dummy.mygate(500)`, we get a `ValueError` that the value is out of bounds, although this would correspond to only 0.5 volts on the instrument. Similarly, if we had scaled the value up in the yaml file, we would now be allowed to exceed the safety range defined by the instrument driver.

@Dominik-Vogel

**Comment by Dominik-Vogel** [comment]
I am looking into this. @WilliamHPNielsen would you agree that this is an issue with the qcodes parameter rather than with the `StationConfigurator`? The station configurator sets the scale correctly. The same behavior is observed here:
```
from qcodes.tests.instrument_mocks import DummyInstrument

d = DummyInstrument(gates=['ch1', 'ch2'])
d.ch1.scale = 0.001
d.ch1(500)
```

Thinking twice about it I am inclined to say that it is probably a matter of taste. I feel that the current implementation is correct: you define a scale for a parameter and the validation takes place on the unscaled value (think about a device that takes mV but you want to define the parameter in V, here you would want to define the limits/validator also in terms of volts)

Now in the presented use case the user probably wants to introduce a new parameter with a different unit and scaling as the original instrument parameter. For this reason I introduced the `DelegateParameter` as a 'proxy'. The delegate parameter has its own scaling and now you can set a limit to the unscaled value on the instrument and to the scaled value of the proxy.

The corresponding yaml file would be:
```
instruments:
  dummy:
    driver: qcodes.tests.instrument_mocks
    type: DummyInstrument
    init:
      gates: ['ch1', 'ch2']

    enable_forced_reconnect: true

    add_parameters:
      mygate_mV:
        source: ch1
        scale: 0.001
        unit: mV
```
